"""Public building blocks for the active-nematic PDE model."""

from .beris_edwards import (
    BerisEdwardsQNonlinearModel,
    STRESS_COMPONENTS,
    beris_edwards_active_stress_components,
    beris_edwards_algebraic_stress_components,
    beris_edwards_distortion_stress_components,
    beris_edwards_flow_alignment_components,
    beris_edwards_free_energy_density,
    beris_edwards_linear_operator,
    beris_edwards_molecular_field_components,
    beris_edwards_q_nonlinear_components,
    beris_edwards_reactive_stress_components,
    q_tensor_contraction,
)
from .fields import Q_COMPONENTS
from .initial_conditions import (
    aligned_x_smooth_noise,
    analytic_periodic_defect_gas_2d,
    available_initial_conditions,
    create_initial_condition,
    extruded_2d_twist,
    neumann_twist_profile,
    sample_periodic_neutral_defects_2d,
)
from .nematics3d_adapter import (
    S_and_director_from_Q,
    director_from_Q,
    eigenframe_from_Q,
    q_field_object_from_Q,
)
from .q_tensor import (
    Q_components,
    Q_convention_metadata,
    Q_magnitude,
    S_from_Q,
    positive_equilibrium_S,
    uniaxial_Q,
)
from .stokes import (
    BerisEdwardsFreeSlipStokes,
    PLANE_DISTORTION_ODD_BOUNDARY_CONDITIONS,
    PLANE_NORMAL_VELOCITY_BOUNDARY_CONDITIONS,
    PLANE_PRESSURE_BOUNDARY_CONDITIONS,
    PLANE_Q_BOUNDARY_CONDITIONS,
    PLANE_TANGENTIAL_VELOCITY_BOUNDARY_CONDITIONS,
)

__all__ = [
    "BerisEdwardsQNonlinearModel",
    "BerisEdwardsFreeSlipStokes",
    "Q_COMPONENTS",
    "STRESS_COMPONENTS",
    "Q_components",
    "Q_convention_metadata",
    "Q_magnitude",
    "PLANE_DISTORTION_ODD_BOUNDARY_CONDITIONS",
    "PLANE_NORMAL_VELOCITY_BOUNDARY_CONDITIONS",
    "PLANE_PRESSURE_BOUNDARY_CONDITIONS",
    "PLANE_Q_BOUNDARY_CONDITIONS",
    "PLANE_TANGENTIAL_VELOCITY_BOUNDARY_CONDITIONS",
    "S_from_Q",
    "S_and_director_from_Q",
    "director_from_Q",
    "eigenframe_from_Q",
    "q_field_object_from_Q",
    "aligned_x_smooth_noise",
    "analytic_periodic_defect_gas_2d",
    "available_initial_conditions",
    "beris_edwards_active_stress_components",
    "beris_edwards_algebraic_stress_components",
    "beris_edwards_distortion_stress_components",
    "beris_edwards_flow_alignment_components",
    "beris_edwards_free_energy_density",
    "beris_edwards_linear_operator",
    "beris_edwards_molecular_field_components",
    "beris_edwards_q_nonlinear_components",
    "beris_edwards_reactive_stress_components",
    "create_initial_condition",
    "extruded_2d_twist",
    "neumann_twist_profile",
    "positive_equilibrium_S",
    "q_tensor_contraction",
    "sample_periodic_neutral_defects_2d",
    "uniaxial_Q",
]
